[I 2024-12-11 16:42:22.714 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-12-11 16:42:22.719 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-12-11 16:42:22.721 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-12-11 16:42:22.721 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2024-12-11 16:42:22.725 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
[W 2024-12-11 16:42:22.725 ServerApp] ServerApp.iopub_data_rate_limit config is deprecated in 2.0. Use ZMQChannelsWebsocketConnection.iopub_data_rate_limit.
[I 2024-12-11 16:42:22.725 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-12-11 16:42:22.733 ServerApp] notebook | extension was successfully linked.
[I 2024-12-11 16:42:23.136 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-12-11 16:42:23.254 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-12-11 16:42:23.258 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-12-11 16:42:23.265 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-12-11 16:42:23.272 LabApp] JupyterLab extension loaded from /Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyterlab
[I 2024-12-11 16:42:23.272 LabApp] JupyterLab application directory is /Users/tparment/miniconda3/envs/nbautoeval/share/jupyter/lab
[I 2024-12-11 16:42:23.279 LabApp] Extension Manager is 'pypi'.
[I 2024-12-11 16:42:23.358 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-12-11 16:42:23.363 ServerApp] notebook | extension was successfully loaded.
[I 2024-12-11 16:42:23.365 ServerApp] Serving notebooks from local directory: /Users/tparment/git/nbautoeval
[I 2024-12-11 16:42:23.365 ServerApp] Jupyter Server 2.14.2 is running at:
[I 2024-12-11 16:42:23.365 ServerApp] http://localhost:64591/lab?token=...
[I 2024-12-11 16:42:23.365 ServerApp]     http://127.0.0.1:64591/lab?token=...
[I 2024-12-11 16:42:23.365 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2024-12-11 16:42:23.817 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-12-11 16:42:54.345 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1733931774336 (aa49911c3df74c1f98f54bb8fe16142d@::1) 2.72ms referer=http://localhost:64591/lab
[W 2024-12-11 16:42:54.346 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1733931774336 (::1): No such file or directory: Untitled.ipynb
[W 2024-12-11 16:42:54.347 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1733931774336 (aa49911c3df74c1f98f54bb8fe16142d@::1) 4.55ms referer=http://localhost:64591/lab
[W 2024-12-11 16:42:54.347 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&hash=0&1733931774336 (::1): No such file or directory: Untitled.ipynb
[I 2024-12-11 16:42:54.439 LabApp] Build is up to date
[W 2024-12-11 16:44:19.175 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:44:20.389 ServerApp] Kernel started: e7849b9d-8692-4534-91d7-52e5ce307368
[I 2024-12-11 16:44:22.176 ServerApp] Connecting to kernel e7849b9d-8692-4534-91d7-52e5ce307368.
[I 2024-12-11 16:44:22.178 ServerApp] Connecting to kernel e7849b9d-8692-4534-91d7-52e5ce307368.
[I 2024-12-11 16:44:22.193 ServerApp] Connecting to kernel e7849b9d-8692-4534-91d7-52e5ce307368.
[W 2024-12-11 16:44:22.221 ServerApp] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x10c4afc50>
[I 2024-12-11 16:44:22.304 ServerApp] Saving file at /tests/essai-exo.ipynb
[W 2024-12-11 16:44:22.311 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:44:25.375 ServerApp] Saving file at /tests/essai-exo.ipynb
[W 2024-12-11 16:44:25.376 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:44:28.411 ServerApp] Saving file at /tests/essai-exo.ipynb
[W 2024-12-11 16:44:28.426 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:44:31.514 ServerApp] Saving file at /tests/essai-exo.ipynb
[W 2024-12-11 16:44:31.514 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:44:34.554 ServerApp] Saving file at /tests/essai-exo.ipynb
[W 2024-12-11 16:44:34.554 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[W 2024-12-11 16:45:53.547 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:45:53.965 ServerApp] Kernel started: 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c
[I 2024-12-11 16:45:54.789 ServerApp] Connecting to kernel 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c.
[I 2024-12-11 16:45:56.695 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:45:56.696 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:45:59.729 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:45:59.729 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:46:02.761 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:46:02.762 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:46:05.794 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:46:05.794 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:46:20.826 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:46:20.827 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:46:23.859 ServerApp] Saving file at /tests/essai-trigger.ipynb
[W 2024-12-11 16:46:23.860 ServerApp] Notebook tests/essai-trigger.ipynb is not trusted
[I 2024-12-11 16:46:26.889 ServerApp] Saving file at /tests/essai-trigger.ipynb
[I 2024-12-11 16:46:41.553 ServerApp] Starting buffering for e7849b9d-8692-4534-91d7-52e5ce307368:33b11b97-4f5e-4c81-bdc8-d0620684ba57
[I 2024-12-11 16:46:41.555 ServerApp] Starting buffering for 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c:2341499d-1561-4150-b2e1-3bd9945cdea5
[W 2024-12-11 16:46:42.807 LabApp] Failed validating settings (jupyterlab-jupytext:plugin): Additional properties are not allowed ('category' was unexpected)
    
    Failed validating 'additionalProperties' in schema:
        {'title': 'Jupytext',
         'description': 'List of Jupytext Text Notebook formats that will be '
                        'added to launcher and jupytext menu.',
         'properties': {'auto:percent': {'type': 'boolean',
                                         'title': 'Text Notebook as Script in '
                                                  'Percent Format',
                                         'default': True},
                        'auto:light': {'type': 'boolean',
                                       'title': 'Text Notebook as Script in '
                                                'Light Format',
                                       'default': False},
                        'auto:hydrogen': {'type': 'boolean',
                                          'title': 'Text Notebook as Script in '
                                                   'Hydrogen Format',
                                          'default': False},
                        'auto:nomarker': {'type': 'boolean',
                                          'title': 'Text Notebook as Script in '
                                                   'Nomarker Format',
                                          'default': False},
                        'md:myst': {'type': 'boolean',
                                    'title': 'MyST Markdown Notebook',
                                    'default': True},
                        'md': {'type': 'boolean',
                               'title': 'Markdown Notebook',
                               'default': False},
                        'Rmd': {'type': 'boolean',
                                'title': 'R Markdown Notebook',
                                'default': False},
                        'qmd': {'type': 'boolean',
                                'title': 'Quarto Markdown Notebook',
                                'default': False},
                        'NOTE': {'description': 'Refresh the current browser '
                                                'tab for the changes to take '
                                                'effect.',
                                 'type': 'null'}},
         'additionalProperties': False,
         'type': 'object'}
    
    On instance:
        {'auto:percent': True,
         'auto:light': False,
         'auto:hydrogen': False,
         'auto:nomarker': False,
         'md:myst': True,
         'md': False,
         'Rmd': False,
         'qmd': False,
         'category': 'Jupytext'}
[I 2024-12-11 16:46:43.183 ServerApp] Connecting to kernel e7849b9d-8692-4534-91d7-52e5ce307368.
[I 2024-12-11 16:46:43.198 ServerApp] Connecting to kernel 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c.
[I 2024-12-11 16:46:43.578 ServerApp] Starting buffering for e7849b9d-8692-4534-91d7-52e5ce307368:3a2b6e4d-3e2e-461b-8e29-321f53f7d6a3
[I 2024-12-11 16:46:43.579 ServerApp] Starting buffering for 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c:35f486eb-07db-4077-89fb-3537abac50df
[I 2024-12-11 16:46:43.942 LabApp] Build is up to date
[W 2024-12-11 16:46:44.179 ServerApp] Notebook tests/essai-exo.ipynb is not trusted
[I 2024-12-11 16:46:44.651 ServerApp] Connecting to kernel e7849b9d-8692-4534-91d7-52e5ce307368.
[I 2024-12-11 16:46:44.670 ServerApp] Connecting to kernel 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c.
[W 2024-12-11 16:46:45.829 ServerApp] 400 GET /api/contents/tests/essai-exo.py?type=notebook&content=1&hash=1&1733932005804 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ...")
[W 2024-12-11 16:46:45.830 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: \'# ---\\\\n# jupyter:\\\\n#   jupytext:\\\\n#    ...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ..."))
[W 2024-12-11 16:46:45.836 ServerApp] 400 GET /api/contents/tests/essai-exo.py?type=notebook&content=1&hash=1&1733932005804 (aa49911c3df74c1f98f54bb8fe16142d@::1) 11.32ms referer=http://localhost:64591/lab/tree/tests/essai-exo.py
[I 2024-12-11 16:47:10.307 ServerApp] Starting buffering for 8ed004d0-19a4-4fc6-a3cd-ff1f31e7cd9c:ba38da28-908b-4706-b327-9394faf9e96c
[I 2024-12-11 16:47:13.819 ServerApp] Starting buffering for e7849b9d-8692-4534-91d7-52e5ce307368:7c65ba73-9730-4f85-b653-4320b150c55c
[W 2024-12-11 16:47:23.078 ServerApp] 400 GET /api/contents/tests/essai-exo.py?type=notebook&content=1&hash=1&1733932043061 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ...")
[W 2024-12-11 16:47:23.078 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: \'# ---\\\\n# jupyter:\\\\n#   jupytext:\\\\n#    ...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/essai-exo.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ..."))
[W 2024-12-11 16:47:23.080 ServerApp] 400 GET /api/contents/tests/essai-exo.py?type=notebook&content=1&hash=1&1733932043061 (aa49911c3df74c1f98f54bb8fe16142d@::1) 7.92ms referer=http://localhost:64591/lab/tree/tests/essai-exo.py
[W 2024-12-11 16:47:48.477 ServerApp] 400 GET /api/contents/tests/notebook-test-content.py?type=notebook&content=1&hash=1&1733932068460 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: '# -*- coding: utf-8 -*-\\n# ---\\n# jupyt...")
[W 2024-12-11 16:47:48.477 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: \'# -*- coding: utf-8 -*-\\\\n# ---\\\\n# jupyt...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: '# -*- coding: utf-8 -*-\\n# ---\\n# jupyt..."))
[W 2024-12-11 16:47:48.479 ServerApp] 400 GET /api/contents/tests/notebook-test-content.py?type=notebook&content=1&hash=1&1733932068460 (aa49911c3df74c1f98f54bb8fe16142d@::1) 6.42ms referer=http://localhost:64591/lab/tree/tests/notebook-test-content.py
[W 2024-12-11 16:48:07.678 ServerApp] 400 GET /api/contents/tests/notebook-test-content.py?type=notebook&content=1&hash=1&1733932087654 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: '# -*- coding: utf-8 -*-\\n# ---\\n# jupyt...")
[W 2024-12-11 16:48:07.679 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: \'# -*- coding: utf-8 -*-\\\\n# ---\\\\n# jupyt...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-content.py NotJSONError("Notebook does not appear to be JSON: '# -*- coding: utf-8 -*-\\n# ---\\n# jupyt..."))
[W 2024-12-11 16:48:07.680 ServerApp] 400 GET /api/contents/tests/notebook-test-content.py?type=notebook&content=1&hash=1&1733932087654 (aa49911c3df74c1f98f54bb8fe16142d@::1) 7.82ms referer=http://localhost:64591/lab/tree/tests/notebook-test-content.py
[W 2024-12-11 16:48:31.353 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-broken.py?type=notebook&content=1&hash=1&1733932111342 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-broken.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ...")
[W 2024-12-11 16:48:31.353 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-broken.py NotJSONError("Notebook does not appear to be JSON: \'# ---\\\\n# jupyter:\\\\n#   jupytext:\\\\n#    ...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-broken.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ..."))
[W 2024-12-11 16:48:31.354 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-broken.py?type=notebook&content=1&hash=1&1733932111342 (aa49911c3df74c1f98f54bb8fe16142d@::1) 4.41ms referer=http://localhost:64591/lab/tree/tests/notebook-test-yaml-broken.py
[W 2024-12-11 16:48:35.738 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-colors.py?type=notebook&content=1&hash=1&1733932115727 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-colors.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ...")
[W 2024-12-11 16:48:35.738 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-colors.py NotJSONError("Notebook does not appear to be JSON: \'# ---\\\\n# jupyter:\\\\n#   jupytext:\\\\n#    ...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-colors.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ..."))
[W 2024-12-11 16:48:35.739 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-colors.py?type=notebook&content=1&hash=1&1733932115727 (aa49911c3df74c1f98f54bb8fe16142d@::1) 4.31ms referer=http://localhost:64591/lab/tree/tests/notebook-test-yaml-colors.py
[W 2024-12-11 16:48:40.125 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-markdown.py?type=notebook&content=1&hash=1&1733932120116 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-markdown.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ...")
[W 2024-12-11 16:48:40.126 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-markdown.py NotJSONError("Notebook does not appear to be JSON: \'# ---\\\\n# jupyter:\\\\n#   jupytext:\\\\n#    ...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/tests/notebook-test-yaml-markdown.py NotJSONError("Notebook does not appear to be JSON: '# ---\\n# jupyter:\\n#   jupytext:\\n#    ..."))
[W 2024-12-11 16:48:40.127 ServerApp] 400 GET /api/contents/tests/notebook-test-yaml-markdown.py?type=notebook&content=1&hash=1&1733932120116 (aa49911c3df74c1f98f54bb8fe16142d@::1) 5.22ms referer=http://localhost:64591/lab/tree/tests/notebook-test-yaml-markdown.py
[W 2024-12-11 16:49:31.147 ServerApp] 400 GET /api/contents/exercises/checkers.py?type=notebook&content=1&hash=1&1733932171126 (::1): Unreadable Notebook: /Users/tparment/git/nbautoeval/exercises/checkers.py NotJSONError("Notebook does not appear to be JSON: '# pylint: disable=c0111\\nimport numpy a...")
[W 2024-12-11 16:49:31.148 ServerApp] wrote error: 'Unreadable Notebook: /Users/tparment/git/nbautoeval/exercises/checkers.py NotJSONError("Notebook does not appear to be JSON: \'# pylint: disable=c0111\\\\nimport numpy a...")'
    Traceback (most recent call last):
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 922, in get
        model = await self._notebook_model(path, content=content, require_hash=require_hash)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 868, in _notebook_model
        nb, bytes_content = await self._read_notebook(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tparment/miniconda3/envs/nbautoeval/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 471, in _read_notebook
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /Users/tparment/git/nbautoeval/exercises/checkers.py NotJSONError("Notebook does not appear to be JSON: '# pylint: disable=c0111\\nimport numpy a..."))
[W 2024-12-11 16:49:31.150 ServerApp] 400 GET /api/contents/exercises/checkers.py?type=notebook&content=1&hash=1&1733932171126 (aa49911c3df74c1f98f54bb8fe16142d@::1) 8.73ms referer=http://localhost:64591/lab/tree/exercises/checkers.py
